# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - githubapigateway

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_81e0886b63234a8083af7f95389c1767 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_2b8012b4bb074d8bac0bd0b8583013f2 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_81e0886b63234a8083af7f95389c1767 }}/api-gateway:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'githubapigateway'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_041bb26dfd76430493892c446286e761 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_81e0886b63234a8083af7f95389c1767 }}/api-gateway:${{ github.sha }}'